-- AlterEnum: Add new stock movement types
ALTER TYPE "StockMovementType" ADD VALUE IF NOT EXISTS 'CORRECTION_LIVRAISON_LOCAL';
ALTER TYPE "StockMovementType" ADD VALUE IF NOT EXISTS 'RETOUR_EXPEDITION';
ALTER TYPE "StockMovementType" ADD VALUE IF NOT EXISTS 'CORRECTION_EXPRESS';
ALTER TYPE "StockMovementType" ADD VALUE IF NOT EXISTS 'AJUSTEMENT';




